environment:
  global:
    CHANS_DEV: "-c pyviz/label/dev"
  matrix:
    - PY: "3.6"
      PYTHON: "C:\\Python36-x64"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda install -y -c pyviz/label/dev pyctdev && doit ecosystem_setup"
  - "conda env create"
  - "activate pyviz"
  - "doit env_capture"

build: off

test_script:
  # (same as python pyviz/download_sample_data.py, but for quick tests)
  - "move examples/data/nyc_taxi_50k.parq examples/data/nyc_taxi_wide.parq"
  - "doit test_examples"
