# file created by pyctdev:
#   doit env_export2 --env-name-again=pyviz --env-file=examples/environment.yml --package-name=pyviz -c pyviz -c defaults --pin-deps

name: pyviz
channels:
  - pyviz
  - defaults
dependencies:
  - bokeh ==0.13.0
  - cartopy
  - cffi
  - dask ==0.18.1
  - datashader ==0.6.7
  - fastparquet
  - geopandas
  - geoviews ==1.5.2
  - holoviews ==1.10.7
  - hvplot ==0.2.1
  - ipython ==5.*
  - ipywidgets ==7.*
  - jupyter
  - netcdf4
  - networkx
  - notebook >=5.4
  - numpy ==1.13.*
  - pandas
  - param ==1.7.0
  - parambokeh ==0.2.3
  - paramnb ==2.0.4
  - phantomjs
  - pyct
  - python ==3.6.*
  - python-snappy
  - rise
  - scikit-image
  - selenium
  - streamz ==0.3.0
  - tornado ==4.5.3
  - xarray
